#!/usr/bin/env python3
"""splat_tools.py -- lossless Gaussian-splat PLY compositing CLI.

A Gaussian splat file is a binary_little_endian PLY whose only element is
`vertex`, each vertex being 62 float32 properties in this exact order:

    x y z nx ny nz f_dc_0..2 f_rest_0..44 opacity scale_0..2 rot_0..3

All operations read/write through a structured numpy dtype over those 62
float32 fields, so bytes that an op does not touch pass through unchanged
(NaNs, denormals, unnormalized quats -- everything survives verbatim).

Subcommands: info, crop, transform, merge, from-points.  Run with -h for
usage on each.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import numpy as np

SH_C0 = 0.28209479177387814

SPLAT_PROPS = (
    ["x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2"]
    + [f"f_rest_{i}" for i in range(45)]
    + ["opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1", "rot_2", "rot_3"]
)
assert len(SPLAT_PROPS) == 62
SPLAT_DTYPE = np.dtype([(name, "<f4") for name in SPLAT_PROPS])  # itemsize 248

_PLY_TYPES = {
    "float": "f4", "float32": "f4", "double": "f8", "float64": "f8",
    "uchar": "u1", "uint8": "u1", "char": "i1", "int8": "i1",
    "ushort": "u2", "uint16": "u2", "short": "i2", "int16": "i2",
    "uint": "u4", "uint32": "u4", "int": "i4", "int32": "i4",
}


# ---------------------------------------------------------------- PLY parsing

def _parse_header(f):
    """Parse a PLY header from an open binary file positioned at start.

    Returns (fmt, vertex_count, properties, comments) where properties is a
    list of (name, ply_type) for the vertex element.  Raises on non-vertex
    elements or list properties (a splat/point PLY has neither).
    """
    if f.readline().strip() != b"ply":
        raise ValueError("not a PLY file (missing 'ply' magic)")
    fmt = None
    vertex_count = None
    properties = []
    comments = []
    current_element = None
    while True:
        line = f.readline()
        if not line:
            raise ValueError("unexpected end of header")
        tokens = line.decode("ascii", "replace").strip().split()
        if not tokens:
            continue
        kw = tokens[0]
        if kw == "comment":
            comments.append(" ".join(tokens[1:]))
        elif kw == "format":
            fmt = tokens[1]
        elif kw == "element":
            current_element = tokens[1]
            if current_element == "vertex":
                vertex_count = int(tokens[2])
            elif int(tokens[2]) != 0:
                raise ValueError(f"unsupported non-empty element '{current_element}'")
        elif kw == "property":
            if current_element == "vertex":
                if tokens[1] == "list":
                    raise ValueError("list property in vertex element")
                properties.append((tokens[-1], tokens[1]))
        elif kw == "end_header":
            break
    if fmt is None or vertex_count is None:
        raise ValueError("header missing format or vertex element")
    return fmt, vertex_count, properties, comments


def read_splat(path):
    """Read a 62-property splat PLY -> (structured array, trailing_bytes)."""
    path = Path(path)
    with open(path, "rb") as f:
        fmt, count, props, _ = _parse_header(f)
        if fmt != "binary_little_endian":
            raise ValueError(f"{path}: expected binary_little_endian, got {fmt}")
        names = [n for n, _ in props]
        types = {t for _, t in props}
        if names != SPLAT_PROPS or types != {"float"}:
            diff = [
                f"  [{i}] expected 'float {e}', got "
                + (f"'{props[i][1]} {props[i][0]}'" if i < len(props) else "nothing")
                for i, e in enumerate(SPLAT_PROPS)
                if i >= len(props) or props[i] != (e, "float")
            ]
            raise ValueError(
                f"{path}: not a 62-float splat header "
                f"({len(props)} properties)\n" + "\n".join(diff[:5])
            )
        payload = f.read(SPLAT_DTYPE.itemsize * count)
        if len(payload) < SPLAT_DTYPE.itemsize * count:
            raise ValueError(
                f"{path}: truncated payload "
                f"({len(payload)} bytes < {SPLAT_DTYPE.itemsize * count})"
            )
        trailing = f.read()
    arr = np.frombuffer(payload, dtype=SPLAT_DTYPE).copy()
    return arr, trailing


def write_splat(path, arr, trailing=b""):
    """Write a structured splat array as a canonical splat PLY."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment Generated by splat_tools.py\n"
        f"element vertex {len(arr)}\n"
        + "".join(f"property float {name}\n" for name in SPLAT_PROPS)
        + "end_header\n"
    )
    with open(path, "wb") as f:
        f.write(header.encode("ascii"))
        f.write(arr.tobytes())
        if trailing:
            f.write(trailing)


def read_points(path):
    """Read a plain point cloud PLY -> (xyz float64 (N,3), rgb01 float64 (N,3)).

    Accepts binary_little_endian or ascii, float or uchar color channels
    (red/green/blue).  Missing colors default to mid-grey.
    """
    path = Path(path)
    with open(path, "rb") as f:
        fmt, count, props, _ = _parse_header(f)
        names = [n for n, _ in props]
        for req in ("x", "y", "z"):
            if req not in names:
                raise ValueError(f"{path}: vertex element has no '{req}' property")
        if fmt == "binary_little_endian":
            dtype = np.dtype([(n, "<" + _PLY_TYPES[t]) for n, t in props])
            raw = np.frombuffer(f.read(dtype.itemsize * count), dtype=dtype)
            if len(raw) < count:
                raise ValueError(f"{path}: truncated payload")
            cols = {n: raw[n].astype(np.float64) for n in names}
        elif fmt == "ascii":
            data = np.loadtxt(f, dtype=np.float64, max_rows=count, ndmin=2)
            cols = {n: data[:, i] for i, n in enumerate(names)}
        else:
            raise ValueError(f"{path}: unsupported PLY format {fmt}")
    xyz = np.column_stack([cols["x"], cols["y"], cols["z"]])
    if all(c in cols for c in ("red", "green", "blue")):
        rgb = np.column_stack([cols["red"], cols["green"], cols["blue"]])
        ply_type = dict(props)["red"]
        if ply_type in ("uchar", "uint8", "char", "int8"):
            rgb = rgb / 255.0
        elif rgb.size and rgb.max() > 1.0:  # float colors stored 0..255
            rgb = rgb / 255.0
    else:
        rgb = np.full_like(xyz, 0.5)
    return xyz, np.clip(rgb, 0.0, 1.0)


# ---------------------------------------------------------------- subcommands

def _fmt_bounds(xyz):
    lo, hi = xyz.min(axis=0), xyz.max(axis=0)
    return (
        f"  min  ({lo[0]:.4f}, {lo[1]:.4f}, {lo[2]:.4f})\n"
        f"  max  ({hi[0]:.4f}, {hi[1]:.4f}, {hi[2]:.4f})\n"
        f"  size ({hi[0]-lo[0]:.4f}, {hi[1]-lo[1]:.4f}, {hi[2]-lo[2]:.4f})"
    )


def cmd_info(args):
    arr, trailing = read_splat(args.input)
    xyz = np.column_stack([arr["x"], arr["y"], arr["z"]]).astype(np.float64)
    print(f"file            {args.input}")
    print(f"gaussians       {len(arr)}")
    print(f"bytes/vertex    {SPLAT_DTYPE.itemsize}")
    print(f"payload bytes   {len(arr) * SPLAT_DTYPE.itemsize}"
          + (f" (+{len(trailing)} trailing)" if trailing else ""))
    print("properties      62 float32, canonical splat order: OK")
    print("bounds")
    print(_fmt_bounds(xyz))
    with np.errstate(over="ignore"):
        alpha = 1.0 / (1.0 + np.exp(-arr["opacity"].astype(np.float64)))
    print(f"opacity(alpha)  mean {alpha.mean():.3f}  min {alpha.min():.3f}  max {alpha.max():.3f}")
    scales = np.exp(np.column_stack(
        [arr["scale_0"], arr["scale_1"], arr["scale_2"]]).astype(np.float64))
    print(f"scale(exp)      mean {scales.mean():.5f}  max {scales.max():.5f}")


def cmd_crop(args):
    arr, trailing = read_splat(args.input)
    x0, y0, z0, x1, y1, z1 = args.box
    lo = np.minimum([x0, y0, z0], [x1, y1, z1])
    hi = np.maximum([x0, y0, z0], [x1, y1, z1])
    inside = (
        (arr["x"] >= lo[0]) & (arr["x"] <= hi[0])
        & (arr["y"] >= lo[1]) & (arr["y"] <= hi[1])
        & (arr["z"] >= lo[2]) & (arr["z"] <= hi[2])
    )
    mask = ~inside if args.invert else inside
    out = arr[mask]
    write_splat(args.output, out, trailing)
    print(f"crop: kept {len(out)} / {len(arr)} gaussians "
          f"({'outside' if args.invert else 'inside'} box) -> {args.output}")


def cmd_transform(args):
    arr, trailing = read_splat(args.input)
    if len(arr) == 0:
        write_splat(args.output, arr, trailing)
        print(f"transform: empty splat copied -> {args.output}")
        return
    xyz = np.column_stack([arr["x"], arr["y"], arr["z"]]).astype(np.float64)

    applied = []
    if args.scale is not None:
        if args.scale <= 0:
            sys.exit("error: --scale must be > 0")
        xyz *= args.scale
        ln_s = np.float32(math.log(args.scale))
        for k in ("scale_0", "scale_1", "scale_2"):
            arr[k] = arr[k] + ln_s
        applied.append(f"scale x{args.scale:g} (log-scales += ln {args.scale:g})")

    if args.rotate_z is not None:
        theta = math.radians(args.rotate_z)
        c, s = math.cos(theta), math.sin(theta)
        xr = c * xyz[:, 0] - s * xyz[:, 1]
        yr = s * xyz[:, 0] + c * xyz[:, 1]
        xyz[:, 0], xyz[:, 1] = xr, yr
        # premultiply each gaussian quaternion (w,x,y,z) by r = rot about +Z
        rw, rz = math.cos(theta / 2.0), math.sin(theta / 2.0)
        w = arr["rot_0"].astype(np.float64)
        x = arr["rot_1"].astype(np.float64)
        y = arr["rot_2"].astype(np.float64)
        z = arr["rot_3"].astype(np.float64)
        arr["rot_0"] = (rw * w - rz * z).astype(np.float32)
        arr["rot_1"] = (rw * x - rz * y).astype(np.float32)
        arr["rot_2"] = (rw * y + rz * x).astype(np.float32)
        arr["rot_3"] = (rw * z + rz * w).astype(np.float32)
        applied.append(f"rotate-z {args.rotate_z:g} deg (positions + quats)")

    if args.translate is not None:
        xyz += np.asarray(args.translate, dtype=np.float64)
        applied.append("translate ({:g}, {:g}, {:g})".format(*args.translate))

    if not applied:
        sys.exit("error: transform needs at least one of "
                 "--translate / --rotate-z / --scale")

    arr["x"] = xyz[:, 0].astype(np.float32)
    arr["y"] = xyz[:, 1].astype(np.float32)
    arr["z"] = xyz[:, 2].astype(np.float32)
    write_splat(args.output, arr, trailing)
    print(f"transform: {len(arr)} gaussians, applied "
          + "; ".join(applied) + f" -> {args.output}")
    print("  (order: scale, then rotate-z, then translate; "
          "rotation/scale are about/relative to the origin)")


def cmd_merge(args):
    arrays = []
    total_trailing = b""
    for p in args.inputs:
        arr, trailing = read_splat(p)  # read_splat enforces the 62-prop header
        arrays.append(arr)
        if trailing:
            print(f"warning: {p} has {len(trailing)} trailing bytes; dropped "
                  "(merge cannot preserve per-file trailing data)", file=sys.stderr)
        print(f"  + {p}: {len(arr)} gaussians")
    out = np.concatenate(arrays)
    write_splat(args.output, out, total_trailing)
    counts = " + ".join(str(len(a)) for a in arrays)
    print(f"merge: {counts} = {len(out)} gaussians -> {args.output}")


def cmd_from_points(args):
    xyz, rgb = read_points(args.input)
    n = len(xyz)
    if n == 0:
        sys.exit(f"error: {args.input} has no points")

    if args.size is not None:
        if args.size <= 0:
            sys.exit("error: --size must be > 0")
        size = args.size
    else:
        diag = float(np.linalg.norm(xyz.max(axis=0) - xyz.min(axis=0)))
        size = 0.005 * diag if diag > 0 else 0.01
    if size <= 0:
        sys.exit("error: computed gaussian size is not positive")

    arr = np.zeros(n, dtype=SPLAT_DTYPE)
    arr["x"] = xyz[:, 0].astype(np.float32)
    arr["y"] = xyz[:, 1].astype(np.float32)
    arr["z"] = xyz[:, 2].astype(np.float32)
    # invert display formula: color = clamp(0.5 + SH_C0 * f_dc)
    f_dc = (rgb - 0.5) / SH_C0
    arr["f_dc_0"] = f_dc[:, 0].astype(np.float32)
    arr["f_dc_1"] = f_dc[:, 1].astype(np.float32)
    arr["f_dc_2"] = f_dc[:, 2].astype(np.float32)
    # f_rest_* stay zero; normals stay zero
    alpha = 0.9
    arr["opacity"] = np.float32(math.log(alpha / (1.0 - alpha)))  # logit
    ln_size = np.float32(math.log(size))
    arr["scale_0"] = arr["scale_1"] = arr["scale_2"] = ln_size
    arr["rot_0"] = np.float32(1.0)  # identity quaternion (w,x,y,z)

    write_splat(args.output, arr)
    print(f"from-points: {n} points -> {n} gaussians ({args.output})")
    print(f"  gaussian size {size:.6f} (ln = {math.log(size):.4f}), "
          f"alpha {alpha} (logit {math.log(alpha/(1-alpha)):.4f}), "
          "identity rotation, f_rest = 0")


def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="splat_tools.py",
        description="Lossless Gaussian-splat PLY compositing (62-float32 layout).",
    )
    sub = ap.add_subparsers(dest="command", required=True)

    p = sub.add_parser("info", help="count, bounds, property check")
    p.add_argument("input")
    p.set_defaults(func=cmd_info)

    p = sub.add_parser("crop", help="keep gaussians inside (or outside) a box")
    p.add_argument("input")
    p.add_argument("output")
    p.add_argument("--box", nargs=6, type=float, required=True,
                   metavar=("X0", "Y0", "Z0", "X1", "Y1", "Z1"))
    p.add_argument("--invert", action="store_true",
                   help="keep gaussians OUTSIDE the box instead")
    p.set_defaults(func=cmd_crop)

    p = sub.add_parser("transform",
                       help="translate / rotate-z / uniform-scale a splat")
    p.add_argument("input")
    p.add_argument("output")
    p.add_argument("--translate", nargs=3, type=float, metavar=("DX", "DY", "DZ"))
    p.add_argument("--rotate-z", type=float, metavar="DEGREES",
                   help="rotate about +Z through the origin; composes into "
                        "positions AND rot quaternions")
    p.add_argument("--scale", type=float, metavar="S",
                   help="uniform scale about the origin; adds ln(S) to scale_0..2")
    p.set_defaults(func=cmd_transform)

    p = sub.add_parser("merge", help="concatenate splats (identical headers)")
    p.add_argument("output")
    p.add_argument("inputs", nargs="+", metavar="input")
    p.set_defaults(func=cmd_merge)

    p = sub.add_parser("from-points",
                       help="convert an x,y,z,rgb point cloud into a splat")
    p.add_argument("input", help="point cloud PLY (editor export / pipeline)")
    p.add_argument("output", help="output splat PLY")
    p.add_argument("--size", type=float, metavar="S",
                   help="isotropic gaussian size (default: 0.5%% of bbox diagonal)")
    p.set_defaults(func=cmd_from_points)

    args = ap.parse_args(argv)
    try:
        args.func(args)
    except (ValueError, OSError) as e:
        sys.exit(f"error: {e}")


if __name__ == "__main__":
    main()
